[server]
headless = true
enableCORS = false
port = 8501

[theme]
base = "light"
primaryColor = "#4CAF50"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F7FB"
textColor = "#262730"
font = "sans serif"
